myweb/Goods_management/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-09 09:39:42

# from framework
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

# create by us
from Goods_management import views
from Goods_management import models
from utils.util import generic_list, generic_detail

urlpatterns = [
    url(r'goods/create/$',
        login_required(views.Master_create.as_view()),
        name='Master_info-create'),
    url(r'goods/$',
        login_required(generic_list),
        {'app': 'goods_management', 'model': models.Master, 'table_name': 'Master_Info'},
        name='goods_info-list'),
    url(r'goods/search/$',
        login_required(generic_list),
        {'app': 'goods_management', 'model': models.Master, 'table_name': 'Master_Info'},
        name='Master-search'),
    url(r'^goods/(?P<pk>\d+)$',
        login_required(generic_detail),
        {'app': 'goods_management', 'model': models.Master, 'table_name': 'Master_Info'},
        name='master-detail'),
    # url(r'order/create/$',
    #     login_required(views.order_create),
    #     name='order_info-create'),

]

myweb/myweb/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-08 20:04:44

# -*- coding: utf-8 -*-

"""myweb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see: 2017-12-11 22:18:59
    https: 2017-12-11 22:18:59
Examples: 2017-12-11 22:18:59
Function views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Class-based views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Including another URLconf
    1. Import the include() function: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
"""

# from framework
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from myweb.views import index, register
from django.contrib.auth.decorators import login_required
# create by us
from myweb.views import index, register

from sales_management import views
from Goods_management import views


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^basic_management/', include('basic_management.urls')),
    url(r'^sales_management/', include('sales_management.urls')),
    url(r'^Goods_management/', include('Goods_management.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^$', login_required(index), name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

myweb/Goods_management/models.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8

from django.db import models
from django.urls import reverse
from basic_management.models import Manufacturer_Information, Employee_Info
from basic_management.models import Categorie


class Master(models.Model):
    # 廠商(名稱、地址、電話)
    T = 'Purchase'
    F = 'Returns'
    Manufacturer_Info = models.ForeignKey(
        Manufacturer_Information,
        models.DO_NOTHING,
        verbose_name='廠商',)

    # 時間
    date = models.DateTimeField('填寫日期',)
    # 經辦人# 驗收人
    # Applicant_staff# Acceptance_staff
    staff = models.ForeignKey(
        Employee_Info,
        models.DO_NOTHING,
        verbose_name='處理人員',)

    contact_person = models.CharField('聯絡人', max_length=16)
    contact_person_phone = models.IntegerField('聯絡電話',)
    remarks = models.TextField('備註', max_length=200, blank=True, null=True)
    address = models.CharField('地址', max_length=200)
    choice = ((T, '進貨'), (F, '退貨'))
    status = models.CharField('進退貨狀態', max_length=16,
                              choices=choice, blank=True)

    class Mate:
        db_table = 'Master_Info'

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('master-detail', args=[str(self.id)])


class Detail(models.Model):
    # 分類
    Categorie = models.ForeignKey(
        Categorie,
        models.DO_NOTHING,
        verbose_name='分類',)
    # 商品名稱
    goods_name = models.CharField('產品名稱', max_length=100)
    # 單位
    unit = models.CharField('單位', max_length=10)
    # 數量
    count = models.IntegerField('數量',)
    # 單價
    price = models.FloatField('單價',)
    # 金額
    amount = models.FloatField('金額',)
    # 被註
    remarks = models.TextField('備註', blank=True, null=True)
    # 總金額
    total_amount = models.FloatField('總金額',)

    class Mate:
        db_table = 'Detail_Info'

    def get_absolute_url(self):
        return reverse('detail_info-update', args=[str(self.id)])


class Purchase_Info(models.Model):

    master = models.ForeignKey(
        Master,
        models.DO_NOTHING,
        verbose_name='單頭',
    )
    detail = models.ForeignKey(
        Detail,
        models.DO_NOTHING,
        verbose_name='單身',
    )

    class Mate:
        db_table = 'Purchase_Info'

    def get_absolute_url(self):
        return reverse('purchase_info-update', args=[str(self.id)])

myweb/Goods_management/views.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-09 09:41:03

from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.forms import extras
from django.http import JsonResponse, HttpResponseRedirect
import datetime
import random
from django.views.generic.edit import FormView

from Goods_management.models import Master, Detail, Purchase_Info
from basic_management.models import Product_Information, Client_Info, Employee_Info, Manufacturer_Information


class MasterForm(forms.Form):
    T = 'Purchase'
    F = 'Out'
    Manufacturer = forms.ChoiceField(
        choices=[(i.id, i.name) for i in Manufacturer_Information.objects.order_by('name')])
    staff = forms.ChoiceField(
        choices=[(i.id, i.name) for i in Employee_Info.objects.order_by('name')])
    contact_person = forms.CharField(label='聯絡人', max_length=16)
    contact_person_phone = forms.IntegerField(label='聯絡人電話',)
    remarks = forms.CharField(label='備註', max_length=200)
    address = forms.CharField(label='地址', max_length=200)
    choice = ((T, '進貨'), (F, '退貨'))
    status = forms.ChoiceField(
        label='進退貨狀態', choices=choice, widget=forms.Select(), required=True)


class Master_create(FormView):
    form_class = MasterForm
    template_name = 'goods_management/Masters_create.html'
    success_url = 'goods/create/'
    model = Product_Information

    def form_valid(self, form):
        Master.objects.create(
            Manufacturer=Manufacturer_Information.objects.get(
                id=form.cleaned_data['Manufacturer']
            ),
            staff=Employee_Info.objects.get(
                id=form.cleaned_data['staff']
            ),
            date=datetime.datetime.now(),
            contact_person=form.cleaned_data['contact_person'],
            contact_person_phone=form.cleaned_data[
                'contact_person_phone'],
            remarks=form.cleaned_data['remarks'],
            address=form.cleaned_data['address'],
            status=form.cleaned_data['status'],

        )
        return self.render_to_response(self.get_context_data())

    # if request.method == 'POST':
    #     return_form = MasterForm(requset.POST)
    # if return_form.is_valid():
    #     Manufacturer = Manufacturer_Info.objects.get(
    #         Manufacturer=return_form.cleaned_data['Manufacturer'])
    #     staff = Employee_Info.objects.get(
    #         staff=return_form.cleaned_data['staff']
    #     )
    #     goods_info = Master(
    #         Manufacturer=Manufacturer,
    #         staff=staff,
    #         date=datetime.datetime.now(),
    #         contact_person=return_form.cleaned_data['contact_person'],
    #         contact_person_phone=return_form.cleaned_data[
    #             'contact_person_phone'],
    #         remarks=return_form.cleaned_data['remarks'],
    #         address=return_form.cleaned_data['address'],
    #         status=return_form.cleaned_data['status'],
    #     )
    #     goods_info.save()

    #     return HttpResponseRedirect(reverse_lazy('goods_info-list'))
    # else:

    # return render(request, 'Goods_management/Masters_create.html', locals())

myweb/sales_management/views.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-20 21:43:49

from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.forms import extras
from django.http import JsonResponse, HttpResponseRedirect
import datetime
import random

from sales_management.models import Order_Info, Order_Detail
from basic_management.models import Product_Information, Client_Info
from django.forms import formset_factory


def order_search(request):

    name = request.GET.get('name')
    client = request.GET.get('client')
    invoice_number = request.GET.get('invoice_number')
    order_list = Order_Info.objects.filter(
        client_id__name__contains=client).filter(id__contains=name).filter(
        invoice_number__contains=invoice_number)
    return render(request,
                  'sales_management/order_infos_search.html',
                  {'order_list': order_list})


class order_details_form(forms.Form):

    product_id_id = forms.ModelChoiceField(label="商品名稱",
                                           queryset=Product_Information.objects.order_by(
                                               'name'),
                                           widget=forms.Select(attrs={'class': 'product'}))

    price = forms.IntegerField(label="售價", min_value=0,
                               initial=0,
                               widget=forms.NumberInput(
                                   attrs={'class': 'price'}))
    num_of_product = forms.IntegerField(label="數量", min_value=0,
                                        initial=0,
                                        widget=forms.NumberInput(
                                            attrs={'class': 'quantity'}))
    subtotal = forms.IntegerField(label="小計", min_value=0, initial=0,
                                  widget=forms.NumberInput(
                                      attrs={'class': 'subtotal'}))
    remark = forms.CharField(label="備註", required=False)


class order_detail_update_form(order_details_form):
    id = forms.CharField()


class order_form(forms.Form):
    current = datetime.datetime.now()

    client = forms.ChoiceField(
        choices=[(i.id, i.name) for i in Client_Info.objects.order_by('name')])

    estimated_shipping_date = forms.DateTimeField(
        label='預計出貨日期',
        widget=forms.extras.SelectDateWidget()
    )
    invoice_number = forms.CharField(label='統一編號', max_length=10)
    delivery_address = forms.CharField(label='送貨地址', max_length=200)
    total = forms.DecimalField(label='合計',
                               max_digits=20,
                               decimal_places=4,
                               initial=0)


def order_create(request):

    menu_item_formset = formset_factory(
        order_details_form,
        extra=2, min_num=1
    )

    form = order_form()
    table_name = "Order create"

    if request.method == 'POST':

        return_form = order_form(request.POST)
        order_formset = menu_item_formset(request.POST, request.FILES)

        if return_form.is_valid() and order_formset.is_valid():

            client = Client_Info.objects.get(
                id=return_form.cleaned_data['client'])
            order_info = Order_Info(
                client_id=client,
                invoice_number=return_form.cleaned_data['invoice_number'],
                date=datetime.datetime.now(),
                estimated_shipping_date=return_form.cleaned_data[
                    'estimated_shipping_date'],
                delivery_address=return_form.cleaned_data['delivery_address'],
                total=return_form.cleaned_data['total']
            )
            order_info.save()

            for form in order_formset:
                Order_Detail.objects.create(
                    product_id=form.cleaned_data['product_id_id'],
                    price=form.cleaned_data['price'],
                    num_of_product=form.cleaned_data['num_of_product'],
                    subtotal=form.cleaned_data['subtotal'],
                    remark=form.cleaned_data['remark'],
                    order_id=order_info
                )

        return HttpResponseRedirect(reverse_lazy('order_info-list'))

    return render(request,
                  'sales_management/order_infos_create.html',
                  locals())


def order_update(request, pk):

    table_name = "Order update"

    if request.method == 'POST':
        return_form = order_form(request.POST)
        formsets = formset_factory(
            order_detail_update_form
        )
        order_formset = formsets(request.POST, request.FILES)

        if return_form.is_valid():
            Order_Info.objects.filter(pk=pk).update(
                client_id=Client_Info.objects.get(
                    id=return_form.cleaned_data['client']),
                estimated_shipping_date=return_form.cleaned_data[
                    'estimated_shipping_date'],
                delivery_address=return_form.cleaned_data['delivery_address'],
                total=return_form.cleaned_data['total'],
                invoice_number=return_form.cleaned_data['invoice_number']
            )

        if order_formset.is_valid():
            for form in order_formset:
                if not form.cleaned_data:
                    break
                detail_id = form.cleaned_data.get('id')
                order_detail = Order_Detail.objects.filter(pk=detail_id).update(
                    product_id=form.cleaned_data['product_id_id'],
                    price=form.cleaned_data['price'],
                    num_of_product=form.cleaned_data['num_of_product'],
                    subtotal=form.cleaned_data['subtotal'],
                    remark=form.cleaned_data['remark']
                )

        return HttpResponseRedirect(reverse_lazy('order_info-list'))
    else:
        order_info = Order_Info.objects.get(id=pk)
        form = order_form(initial={
            'client': order_info.client_id,
            'estimated_shipping_date': order_info.estimated_shipping_date,
            'delivery_address': order_info.delivery_address,
            'total': order_info.total,
            'invoice_number': order_info.invoice_number
        })

        order_details = Order_Detail.objects.filter(order_id=pk).values()
        formsets = formset_factory(
            order_detail_update_form, min_num=1
        )
        menu_item_formset = formsets(initial=order_details)

        return render(request, 'sales_management/order_infos_update.html', locals())


class OrderDelete(PermissionRequiredMixin, DeleteView):
    model = Order_Info
    template_name = 'generic_confirm_delete.html'
    success_url = reverse_lazy('order_info-list')
    permission_required = 'sales_management.delete_order_info'

    def get_context_data(self, **kwargs):
        context = super(OrderDelete, self).get_context_data(**kwargs)
        context['table_name'] = 'Order info'
        return context


class OrderDetailDelete(PermissionRequiredMixin, DeleteView):
    model = Order_Detail
    template_name = 'generic_confirm_delete.html'
    permission_required = 'sales_management.delete_order_detail'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailDelete, self).get_context_data(**kwargs)
        context['table_name'] = 'Order detail'
        return context

    def get_success_url(self):
        order = self.object.order_id
        return reverse_lazy('order_info-update', kwargs={'pk': order.id})

myweb/templates/goods_management/Masters_create.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}
{% block javascript %}
var intId=1;
function add_new_data() {
    var num = document.getElementById("order_details_table").rows.length;
    intId=num;
    var Tr = document.getElementById("order_details_table").insertRow(num);
    Td = Tr.insertCell(Tr.cells.length);
    Td.innerHTML='<select name="key[]"> {% for i in product_list %} <option value="{{i.id}}">{{i.name}}</option> {% endfor %} </select> ';
    Td = Tr.insertCell(Tr.cells.length);
    Td.innerHTML='<input name="price[]" type="text" size="12" class="product_price" id="price'+intId+'" onchange="c('+intId+')" value="0">';
    Td = Tr.insertCell(Tr.cells.length);
    Td.innerHTML='<input name="amount[]" type="text" size="12" class="product_amount" id="amount'+intId+'" onchange="c('+intId+')" value="0">';
    Td = Tr.insertCell(Tr.cells.length);
    Td.innerHTML='<input name="subtotal[]" type="text" size="12" class="product_subtotal" id="subtotal'+intId+'" onchange="total_price()" value="0">';
    Td = Tr.insertCell(Tr.cells.length);
    Td.innerHTML='<input name="remark[]" type="text" size="12">';
}

    function c(Id){
            // var price=$(this).next().val();
            // var price=$(this).siblings('#price').val();
            // var num =$(this).siblings('#num').val();
            // var num=$(this).prev();
            var price =$('tr').find('#price'+Id).val();
            var num = $('tr').find('#amount'+Id).val();
            var amount =price*num;
            
            // $('tr.fieldwrapper').find('.amount').val(amount);
            $('tr').find('#subtotal'+Id).val(amount);
            total_price();
        }
    function total_price(){
        var total_price=0
        for (i=1;i<=intId;i++){
        
        var price=$('#subtotal'+i).val();
        total_price=parseInt(total_price)+parseInt(price);
        }

        
        $('#id_total').val(total_price);
    }



function remove_data() {
    intId--
    var num = document.getElementById("order_details_table").rows.length;
    if(num > 2)
    {
    // remove the last row
     document.getElementById("order_details_table").deleteRow(-1);
    }
    total_price();

}
{% endblock %}
{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
    
    <div class="div-menu">
        <h2>銷貨狀態</h2>
        <form action="" method="post">
    {% csrf_token %}
        <table>
            <tr>
                <th><label>廠商</label></th>
                <td>{{ form.Manufacturer }}</td>
            </tr>
            <tr>
                <th><label>經辦員工</label></th>
                <td>{{ form.staff }}</td>
            </tr>
            <tr>
                <th><label>聯絡人</label></th>
                <td>{{ form.contact_person }}</td>
            </tr>
            <tr>
                <th><label>聯絡人電話</label></th>
                <td>{{ form.contact_person_phone }}</td>
            </tr>
            <tr>
                <th><label>地址</label></th>
                <td>{{ form.address }}</td>
            </tr>
            <tr>
                <th><label>備註</label></th>
                <td>{{ form.remarks }}</td>
            </tr>
            </table>
            <table id="order_details_table">
        <tr>
            <th>商品名稱</th>
            <th>售價</th>
            <th>數量</th>
            <th>小計</th>
            <th>備註</th>
        </tr>
        <tr >
            <td>
                <select name="key[]">
                {% for i in Product_Information %}
                <option value="{{i.id}}">{{i.name}}</option>
                {% endfor %}
                </select>
            </td>
            <td>
                <input type="text" name="price[]" class="product_price" id="price1" onchange="c(1)" size=12 value="0">
            </td>
            <td>
                <input type="text" name="amount[]" class="product_amount" id="amount1" onchange="c(1)" size=12 value="0">
            </td>
            <td>
                <input type="text" name="subtotal[]" class="product_subtotal" id="subtotal1" onchange="total_price()" value="0"  size=12>
            </td>
            <td>
                <input type="text" name="remark[]" size=12>
            </td>
        </tr>
            </table>
    <input value="increase" onclick="add_new_data()" type="button">
    <input value="decrease" onclick="remove_data()" type="button">
    <br>
    <label>合計</label> {{ form.total }}
    <br>
    <input type="submit" value="Submit" id="ajax_post_test"/>
    </tr>
            
        </form>
    </div>

    <a href="{% url 'goods_info-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/goods_management/Masters_detail.html
{% extends 'base.html' %}

{% block title %}Details of client{% endblock %}

{% block content %}

<h2>{{table_name}}</h2>

    {% if object %}
    <p><strong>廠商:</strong>{{ object.Manufacturer_Info }}</p>
    <p><strong>填寫日期:</strong>{{ object.date }}</p>
    <p><strong>處理人員:</strong>{{ object.staff }}</p>
    <p><strong>聯絡人:</strong>{{ object.contact_person }}</p>
    <p><strong>聯絡電話:</strong>{{ object.contact_person_phone }}</p>
    <p><strong>備註:</strong>{{ object.remarks }}</p>
    <p><strong>地址:</strong>{{ object.address }}</p>
    <p><strong>進退貨狀態:</strong>{{ object.status }}</p>
    
    {% else %}
        <p>No detail of client.</p>
    {% endif %}
    
    {% if perms.basic_management.add_master %}
    <a href="{% url 'Master_info-create' %}" target="_blank">Create new Purchase</a>
    {% endif %}
{% endblock %}

myweb/templates/goods_management/Masters_list.html
{% extends 'generic_list_base.html' %}
{% block title %}List Master info{% endblock %}
{% block create_button %}
{% if perms.Goods_management.add_master %}
<a href="{% url 'Master_info-create' %}" target="_blank">Create Master info</a>
{% endif %}
<div>
   <form action="{% url 'Master-search'  %}" method="get">
      {% csrf_token %}
        編號
        <input type="text" name="name" id='name' placeholder="輸入">
        客戶
        <input type="text" name="client" id='name' placeholder="輸入">
        統編
        <input type="text" name="invoice_number" id='name' placeholder="輸入">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</div>
{% endblock %}

{% block table %}

    <table>
        <tr>
        <th>廠商</th>
        <th>經辦人</th>
        <th>Date</th>

        </tr>
        {% for object in objects %}
        <tr>
        <td><a href="{{object.get_absolute_url}}" target="_blank">{{object.Manufacturer_Info}}</a></td>
        <td>{{object.staff}}</td>
        <td>{{object.date}}</td>

        </tr>
        {% endfor %}
    </table>
{% endblock %}

myweb/templates/goods_management/masters_detail.html
{% extends 'base.html' %}

{% block title %}Details of client{% endblock %}

{% block content %}

<h2>{{table_name}}</h2>

    {% if object %}
    <p><strong>廠商:</strong>{{ object.Manufacturer_Info }}</p>
    <p><strong>填寫日期:</strong>{{ object.date }}</p>
    <p><strong>處理人員:</strong>{{ object.staff }}</p>
    <p><strong>聯絡人:</strong>{{ object.contact_person }}</p>
    <p><strong>聯絡電話:</strong>{{ object.contact_person_phone }}</p>
    <p><strong>備註:</strong>{{ object.remarks }}</p>
    <p><strong>地址:</strong>{{ object.address }}</p>
    <p><strong>進退貨狀態:</strong>{{ object.status }}</p>
    
    {% else %}
        <p>No detail of client.</p>
    {% endif %}
    
    {% if perms.basic_management.add_master %}
    <a href="{% url 'Master_info-create' %}" target="_blank">Create new Purchase</a>
    {% endif %}
{% endblock %}

myweb/templates/goods_management/masters_list.html
{% extends 'generic_list_base.html' %}
{% block title %}List Master info{% endblock %}
{% block create_button %}
{% if perms.Goods_management.add_master %}
<a href="{% url 'Master_info-create' %}" target="_blank">Create Master info</a>
{% endif %}
<div>
   {% comment %}
   <form action="{% url 'Master-search'  %}" method="get">
      {% csrf_token %}
        編號
        <input type="text" name="name" id='name' placeholder="輸入">
        客戶
        <input type="text" name="client" id='name' placeholder="輸入">
        統編
        <input type="text" name="invoice_number" id='name' placeholder="輸入">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>
   {% endcomment %}
</div>
{% endblock %}

{% block table %}

    <table>
        <tr>
        <th>廠商</th>
        <th>經辦人</th>
        <th>Date</th>

        </tr>
        {% for object in objects %}
        <tr>
        <td><a href="{{object.get_absolute_url}}" target="_blank">{{object.Manufacturer_Info}}</a></td>
        <td>{{object.staff}}</td>
        <td>{{object.date}}</td>

        </tr>
        {% endfor %}
    </table>
{% endblock %}

myweb/templates/goods_management/purchase_info.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
        <script type="text/javascript">
        	$(document).ready(function() {
	    $("#add").click(function() {
	    		var lastField = $("#buildyourform div:last");
	        var intId = (lastField && lastField.length && lastField.data("idx") + 1) || 1;
	        
	        var fieldWrapper = $("<tr class=\"fieldwrapper\" id=" + intId + "/>");
	        fieldWrapper.data("idx", intId);
	        var fName = $("<td><input type=\"text\" class=\"fieldname\" /> </td>");
	        var fName1 = $("<td><input type=\"text\" class=\"fieldname\" /> </td>");
	        var fName2 = $("<td><input type=\"text\" class=\"fieldname\" /> </td>");
	        var fName3 = $("<td><input type=\"text\" class=\"fieldname\" /> </td>");
	        var fName4 = $("<td><input type=\"text\" class=\"fieldname\" /> </td>");
	        var removeButton = $("<input type=\"button\" class=\"remove\" value=\"-\" />");
	        removeButton.click(function() {
	            $(this).parent().remove();
	        });
	        fieldWrapper.append(fName);
	        fieldWrapper.append(fName1);
	        fieldWrapper.append(fName2);
	        fieldWrapper.append(fName3);
	        fieldWrapper.append(fName4);
	        
	        fieldWrapper.append(removeButton);
	        
	        $("#buildyourform table").append(fieldWrapper);
	    });
	    // $("#preview").click(function() {
	    //     $("#yourform").remove();
	    //     var fieldSet = $("<fieldset id=\"yourform\"><legend>Your Form</legend></fieldset>");
	    //     $("#buildyourform div").each(function() {
	    //         var id = "input" + $(this).attr("id").replace("field","");
	    //         var label = $("<label for=\"" + id + "\">" + $(this).find("input.fieldname").first().val() + "</label>");
	    //         var input;
	    //         switch ($(this).find("select.fieldtype").first().val()) {
	    //             case "checkbox":
	    //                 input = $("<input type=\"checkbox\" id=\"" + id + "\" name=\"" + id + "\" />");
	    //                 break;
	    //             case "textbox":
	    //                 input = $("<input type=\"text\" id=\"" + id + "\" name=\"" + id + "\" />");
	    //                 break;
	    //             case "textarea":
	    //                 input = $("<textarea id=\"" + id + "\" name=\"" + id + "\" ></textarea>");
	    //                 break;    
	    //         }
	    //         fieldSet.append(label);
	    //         fieldSet.append(input);
	    //     });
	    //     $("body").append(fieldSet);
	    // });
	});

        </script>

</head>
<body>

	


	<form id="buildyourform">
		<legend>Build your own form!</legend>
		<table class="table table-bordered " >
	<tr>
			
			<th>品名</th>
			<th>單位</th>
			<th>數量</th>
			<th>單價</th>
			<th>金額</th>
			<th>備註</th>
    	</tr>
    	</table>
	</form>
	<input type="button" value="Preview form" class="add" id="preview" />
	<input type="button" value="Add a field" class="add" id="add" />

</body>
</html>