myweb/myweb/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-08 20:04:44

# -*- coding: utf-8 -*-

"""myweb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see: 2017-12-11 22:18:59
    https: 2017-12-11 22:18:59
Examples: 2017-12-11 22:18:59
Function views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Class-based views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Including another URLconf
    1. Import the include() function: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
"""

# from framework
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from myweb.views import index, register
from django.contrib.auth.decorators import login_required
# create by us
from myweb.views import index, register

from sales_management import views
from Goods_management import views


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^basic_management/', include('basic_management.urls')),
    url(r'^sales_management/', include('sales_management.urls')),
    url(r'^Goods_management/', include('Goods_management.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^$', login_required(index), name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

myweb/sales_management/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-17 19:37:50

# from framework
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

# create by us
from sales_management import views
from sales_management import models
from utils.util import generic_list

urlpatterns = [
    url(r'order/create/$',
        login_required(views.order_create),
        name='order_info-create'),
    url(r'order/(?P<pk>\d+)/update/$',
        login_required(views.order_update),
        name='order_info-update'),
    url(r'order/(?P<pk>\d+)/delete/$',
        login_required(views.OrderDelete.as_view()),
        name='order_info-delete'),
    url(r'^order/$',
        login_required(generic_list),
        {'app': 'sales_management', 'model': models.Order_Info, 'table_name': 'Order info'},
        name='order_info-list'),
    url(r'^order/search/$',
        login_required(views.order_search),
        name='order-search'),
    url(r'order_detail/(?P<pk>\d+)/delete/$',
        login_required(views.OrderDetailDelete.as_view()),
        name='order_detail-delete'),
]

myweb/sales_management/models.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-16 12:17:03

from django.db import models
from django.urls import reverse
from basic_management.models import Client_Info
from basic_management.models import Product_Information


class Order_Info(models.Model):

    client_id = models.ForeignKey(
        Client_Info, on_delete=models.CASCADE, verbose_name='客戶id')
    invoice_number = models.CharField(verbose_name='統一編號', max_length=10)
    date = models.DateTimeField(verbose_name='輸入日期')
    estimated_shipping_date = models.DateTimeField(verbose_name='預計出貨日期')
    delivery_address = models.CharField(verbose_name='送貨地址', max_length=200)
    total = models.DecimalField(
        max_digits=20, decimal_places=4, verbose_name='合計')

    class Mate:
        db_table = 'Order_Info'

    def get_absolute_url(self):
        return reverse('order_info-update', args=[str(self.id)])

    def __str__(self):
        return '訂貨單號:{}'.format(self.id)


class Sales_Info(models.Model):

    date = models.DateTimeField(verbose_name='日期')
    client_id = models.ForeignKey(
        Client_Info, on_delete=models.CASCADE, verbose_name='客戶')
    total = models.DecimalField(
        max_digits=20, decimal_places=4, verbose_name='合計')

    class Mate:
        db_table = 'Sales_Info'

    def __str__(self):
        return '出貨單號:{}'.format(self.id)


class Returns_Info(models.Model):

    RETURNS_TYPES = (('E', 'Exchange'), ('R', 'Return'))

    date = models.DateTimeField(verbose_name='日期')
    client_id = models.ForeignKey(
        Client_Info, on_delete=models.CASCADE, verbose_name='會員編號')
    returns_reason = models.TextField(verbose_name='退貨原因', max_length=500)
    returns_type = models.CharField(
        max_length=2, choices=RETURNS_TYPES, default='E', verbose_name='退/換貨')
    total = models.IntegerField(verbose_name='合計')

    class Mate:
        db_table = 'Returns_Info'

    def get_absolute_url(self):
        return reverse('Returns_Info-detail', args=[str(self.id)])

    def __str__(self):
        return '退貨單號:{}'.format(self.id)


class Details_base(models.Model):

    product_id = models.ForeignKey(
        Product_Information, on_delete=models.CASCADE, verbose_name='商品id')
    price = models.IntegerField(verbose_name='售價')
    num_of_product = models.IntegerField(verbose_name='數量')
    subtotal = models.IntegerField(verbose_name='小計')
    remark = models.TextField(verbose_name='備註', null=True)

    class Mate:
        abstract = True
        ordering = ['id']


class Order_Detail(Details_base):
    order_id = models.ForeignKey(
        Order_Info, on_delete=models.CASCADE, verbose_name='訂貨單號')

    class Mate:
        db_table = 'Order_Details'


class Sales_Detail(Details_base):

    sales_id = models.ForeignKey(
        Sales_Info, on_delete=models.CASCADE, verbose_name='出貨單號')

    class Mate:
        db_table = 'Sales_Details'


class Returns_Detail(Details_base):

    returns_id = models.ForeignKey(
        Returns_Info, on_delete=models.CASCADE, verbose_name='退貨單號')

    class Mate:
        db_table = 'Returns_Details'

myweb/sales_management/views.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-20 21:43:49

from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.forms import extras
from django.http import JsonResponse, HttpResponseRedirect
import datetime
import random

from sales_management.models import Order_Info, Order_Detail
from basic_management.models import Product_Information, Client_Info
from django.forms import formset_factory


def order_search(request):

    name = request.GET.get('name')
    client = request.GET.get('client')
    invoice_number = request.GET.get('invoice_number')
    order_list = Order_Info.objects.filter(
        client_id__name__contains=client).filter(id__contains=name).filter(
        invoice_number__contains=invoice_number)
    return render(request,
                  'sales_management/order_infos_search.html',
                  {'order_list': order_list})


class order_details_form(forms.Form):

    product_id_id = forms.ModelChoiceField(label="商品名稱",
                                           queryset=Product_Information.objects.order_by(
                                               'name'),
                                           widget=forms.Select(attrs={'class': 'product'}))

    price = forms.IntegerField(label="售價", min_value=0,
                               initial=0,
                               widget=forms.NumberInput(
                                   attrs={'class': 'price'}))
    num_of_product = forms.IntegerField(label="數量", min_value=0,
                                        initial=0,
                                        widget=forms.NumberInput(
                                            attrs={'class': 'quantity'}))
    subtotal = forms.IntegerField(label="小計", min_value=0, initial=0,
                                  widget=forms.NumberInput(
                                      attrs={'class': 'subtotal'}))
    remark = forms.CharField(label="備註", required=False)


class order_detail_update_form(order_details_form):
    id = forms.CharField()


class order_form(forms.Form):
    current = datetime.datetime.now()

    client = forms.ChoiceField(
        choices=[(i.id, i.name) for i in Client_Info.objects.order_by('name')])

    estimated_shipping_date = forms.DateTimeField(
        label='預計出貨日期',
        widget=forms.extras.SelectDateWidget()
    )
    invoice_number = forms.CharField(label='統一編號', max_length=10)
    delivery_address = forms.CharField(label='送貨地址', max_length=200)
    total = forms.DecimalField(label='合計',
                               max_digits=20,
                               decimal_places=4,
                               initial=0)


def order_create(request):

    menu_item_formset = formset_factory(
        order_details_form,
        extra=2, min_num=1
    )

    form = order_form()
    table_name = "Order create"

    if request.method == 'POST':

        return_form = order_form(request.POST)
        order_formset = menu_item_formset(request.POST, request.FILES)

        if return_form.is_valid() and order_formset.is_valid():

            client = Client_Info.objects.get(
                id=return_form.cleaned_data['client'])
            order_info = Order_Info(
                client_id=client,
                invoice_number=return_form.cleaned_data['invoice_number'],
                date=datetime.datetime.now(),
                estimated_shipping_date=return_form.cleaned_data[
                    'estimated_shipping_date'],
                delivery_address=return_form.cleaned_data['delivery_address'],
                total=return_form.cleaned_data['total']
            )
            order_info.save()

            for form in order_formset:
                Order_Detail.objects.create(
                    product_id=form.cleaned_data['product_id_id'],
                    price=form.cleaned_data['price'],
                    num_of_product=form.cleaned_data['num_of_product'],
                    subtotal=form.cleaned_data['subtotal'],
                    remark=form.cleaned_data['remark'],
                    order_id=order_info
                )

        return HttpResponseRedirect(reverse_lazy('order_info-list'))

    return render(request,
                  'sales_management/order_infos_create.html',
                  locals())


def order_update(request, pk):

    table_name = "Order update"

    if request.method == 'POST':
        return_form = order_form(request.POST)
        formsets = formset_factory(
            order_detail_update_form
        )
        order_formset = formsets(request.POST, request.FILES)

        if return_form.is_valid():
            Order_Info.objects.filter(pk=pk).update(
                client_id=Client_Info.objects.get(
                    id=return_form.cleaned_data['client']),
                estimated_shipping_date=return_form.cleaned_data[
                    'estimated_shipping_date'],
                delivery_address=return_form.cleaned_data['delivery_address'],
                total=return_form.cleaned_data['total'],
                invoice_number=return_form.cleaned_data['invoice_number']
            )

        if order_formset.is_valid():
            for form in order_formset:
                if not form.cleaned_data:
                    break
                detail_id = form.cleaned_data.get('id')
                order_detail = Order_Detail.objects.filter(pk=detail_id).update(
                    product_id=form.cleaned_data['product_id_id'],
                    price=form.cleaned_data['price'],
                    num_of_product=form.cleaned_data['num_of_product'],
                    subtotal=form.cleaned_data['subtotal'],
                    remark=form.cleaned_data['remark']
                )

        return HttpResponseRedirect(reverse_lazy('order_info-list'))
    else:
        order_info = Order_Info.objects.get(id=pk)
        form = order_form(initial={
            'client': order_info.client_id,
            'estimated_shipping_date': order_info.estimated_shipping_date,
            'delivery_address': order_info.delivery_address,
            'total': order_info.total,
            'invoice_number': order_info.invoice_number
        })

        order_details = Order_Detail.objects.filter(order_id=pk).values()
        formsets = formset_factory(
            order_detail_update_form, min_num=1
        )
        menu_item_formset = formsets(initial=order_details)

        return render(request, 'sales_management/order_infos_update.html', locals())


class OrderDelete(PermissionRequiredMixin, DeleteView):
    model = Order_Info
    template_name = 'generic_confirm_delete.html'
    success_url = reverse_lazy('order_info-list')
    permission_required = 'sales_management.delete_order_info'

    def get_context_data(self, **kwargs):
        context = super(OrderDelete, self).get_context_data(**kwargs)
        context['table_name'] = 'Order info'
        return context


class OrderDetailDelete(PermissionRequiredMixin, DeleteView):
    model = Order_Detail
    template_name = 'generic_confirm_delete.html'
    permission_required = 'sales_management.delete_order_detail'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailDelete, self).get_context_data(**kwargs)
        context['table_name'] = 'Order detail'
        return context

    def get_success_url(self):
        order = self.object.order_id
        return reverse_lazy('order_info-update', kwargs={'pk': order.id})

myweb/templates/sales_management/order_infos_create.html
{% extends 'base.html' %}
{% block javascript %}

$(document).ready(function(){
    $('.menu-item-add').click(function (e) {
        e.preventDefault();

        var lastElement = $('.menu-item:last');
        var totalForms = $('#id_form-TOTAL_FORMS');
        var total = parseInt(totalForms.val());

        var newElement = lastElement.clone(true);
        newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace(
          '-' + (total - 1) + '-',
          '-' + total + '-'
        );
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id});
        });

		/* replace previous id */
        newElement.find('label').each(function() {
        $(this).attr('for', $(this).attr('for').replace(
          '-' + (total - 1) + '-',
          '-' + total + '-'
            ));
        });

        totalForms.val(total + 1);
        newElement.insertAfter(lastElement);
    });

    $('.price, .quantity').change(function(){
        $('.menu-item').each(function(){
            var price = jQuery(this).children('.price').val();
            var quantity = jQuery(this).children('.quantity').val();
            var subtotal = parseInt(price)*parseInt(quantity);
            jQuery(this).children('.subtotal').val(subtotal);
        });

        total_price();
    });

    $('.subtotal').change(function(){
        total_price();
    });

    $('.product').change(function(){
        var product_id = $(this).val();
        var price = jQuery(this).siblings(".price");

        $.ajax({
            method:"GET",
            url:"{% url 'product_price_request' %}",
            data:{"product_id":product_id}
        }).done(function(data){
               price.val(data["price"]);
        });
    });
});

function total_price(){
    var sum = 0;
    $('.subtotal').each(function() {
    sum += Number($(this).val());
    });

    $('input[name="total"]').val(sum);
}

function remove_data() {
    var lastElement = $('.menu-item:last');
    var totalForms = $('#id_form-TOTAL_FORMS');
    var total = parseInt(totalForms.val());

    if(total > 1)
    {
    /* remove last div */
    lastElement.remove();
    }
    total_price();
    totalForms.val(total - 1);
}

$.ajaxSetup({
    data:{
        csrfmiddlewaretoken:'{{ csrf_token }}'
    },
});

{% endblock %}
{% block title %}{{ table_name }}{% endblock %}
{% block content %}

<form action="{% url 'order_info-create' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
        <th><label>Client</label></th>
        <td>{{ form.client }}</td>
        </tr>
        <tr>
        <th><label>預計出貨日期</label></th>
        <td>{{ form.estimated_shipping_date }}</td>
        </tr>
        <tr>
        <th><label>送貨地址</label></th>
        <td>{{ form.delivery_address }}</td>
        </tr>
        <tr>
        <th><label>統一編號</label></th>
        <td>{{ form.invoice_number }}</td>
        </tr>
    </table>

	{{ menu_item_formset.management_form }}
    {% for form in menu_item_formset %}
    <div class="menu-item form-group">
		{{ form.as_table }}
    </div>
	{% endfor %}
    <input value="新增項目" type="button" class="menu-item-add">
    <input value="減少項目" onclick="remove_data()" type="button">
    <br>
    <label>合計</label> {{ form.total }}
    <br>
    <input type="submit" value="Submit"/>
    </tr>
</form>

{% endblock %}

myweb/templates/sales_management/order_infos_list.html
{% extends 'generic_list_base.html' %}
{% block title %}List order info{% endblock %}
{% block create_button %}
{% if perms.sales_management.add_order_info %}
<a href="{% url 'order_info-create' %}" target="_blank">Create order info</a>
{% endif %}
<div>
   <form action="{% url 'order-search'  %}" method="get">
      {% csrf_token %}
        編號
        <input type="text" name="name" id='name' placeholder="輸入">
        客戶
        <input type="text" name="client" id='name' placeholder="輸入">
        統編
        <input type="text" name="invoice_number" id='name' placeholder="輸入">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</div>
{% endblock %}

{% block table %}

    <table>
        <tr>
        <th>Client name</th>
        <th>Invoice number</th>
        <th>Date</th>
        {% if perms.sales_management.delete_order_info %}
        <th>Delete</th>
        {% endif %}
        </tr>
        {% for object in objects %}
        <tr>
            <td><a {% if perms.sales_management.change_order_info %} href="{{object.get_absolute_url}}{% endif %}" target="_blank">{{object.client_id}}</a></td>
        <td>{{object.invoice_number}}</td>
        <td>{{object.date}}</td>
        {% if perms.sales_management.delete_order_info %}
        <td><a href="{% url 'order_info-delete' pk=object.id %}" target="_blank">Delete</a></td>
        {% endif %}
        </tr>
        {% endfor %}
    </table>
{% endblock %}

myweb/templates/sales_management/order_infos_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>銷貨狀態</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>編號</th>
			<th>客戶</th>			
			<th>統編</th>
			<th>出貨日</th>
			<th>地址</th>
			<th>金額</th>

		</tr>
		{%for e in order_list%}
		<tr>

			<td><a href="/sales_management/order/{{e.id}}/update/">{{e.id}}</a></td>
			<td>{{e.client_id}}</td>
			<td>{{e.invoice_number}}</td>		
			<td>{{e.estimated_shipping_date}}</td>
			<td>{{e.delivery_address}}</td>
			<td>{{e.total}}</td>


		</tr>
		{% endfor %}

		</table>

	</div>

	<a href="{% url 'order_info-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/sales_management/order_infos_update.html
{% extends 'base.html' %} 
{% block javascript %}

$(document).ready(function(){
    $('.price, .quantity').change(function(){
        $('.menu-item').each(function(){
            var price = jQuery(this).children('.price').val();
            var quantity = jQuery(this).children('.quantity').val();
            var subtotal = parseInt(price)*parseInt(quantity);
            jQuery(this).children('.subtotal').val(subtotal);
        });

        total_price();
    });

    $('.subtotal').change(function(){
        total_price();
    });

    $('.product').change(function(){
        var product_id = $(this).val();
        var price = jQuery(this).siblings(".price");

        $.ajax({
            method:"GET",
            url:"{% url 'product_price_request' %}",
            data:{"product_id":product_id}
        }).done(function(data){
               price.val(data["price"]);
        });
    });
});

function total_price(){
    var sum = 0;
    $('.subtotal').each(function() {
    sum += Number($(this).val());
    });

    $('input[name="total"]').val(sum);
}

function remove_data() {
    var lastElement = $('.menu-item:last');
    var totalForms = $('#id_form-TOTAL_FORMS');
    var total = parseInt(totalForms.val());

    if(total > 1)
    {
    /* remove last div */
    lastElement.remove();
    }
    total_price();
    totalForms.val(total - 1);
}

$.ajaxSetup({
    data:{
        csrfmiddlewaretoken:'{{ csrf_token }}'
    },
});

{% endblock %}
{% block title %} {{ table_name }} {% endblock %} 
{% block content %}

<form action="{% url 'order_info-update' pk=pk %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
        <th><label>Client</label></th>
        <td>{{ form.client }}</td>
        </tr>
        <tr>
        <th><label>預計出貨日期</label></th>
        <td>{{ form.estimated_shipping_date }}</td>
        </tr>
        <tr>
        <th><label>送貨地址</label></th>
        <td>{{ form.delivery_address }}</td>
        </tr>
        <tr>
        <th><label>統一編號</label></th>
        <td>{{ form.invoice_number }}</td>
        </tr>
    </table>

	{{ menu_item_formset.management_form }}
    {% for form in menu_item_formset %}
    <div class="menu-item form-group">
        <label>商品名稱</label>
		{{ form.product_id_id }}
        <label>售價</label>
		{{ form.price }}
        <label>數量</label>
		{{ form.num_of_product }}
        <label>小計</label>
		{{ form.subtotal }}
        <label>備註</label>
		{{ form.remark }}
		{{ form.id.as_hidden }}
    </div>
	{% endfor %}
    <label>合計</label> {{ form.total }}
    <br>
    <input type="submit" value="Update"/>
    </tr>
</form>
{% if perms.sales_management.delete_order_info %}
<a href="{% url 'order_info-delete' pk=pk %}" target="_blank">Delete</a>
{% endif %} 
{% endblock %}