myweb/basic_management/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-17 20:02:34

"""myweb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see: 2017-12-11 22:15:19
    https: 2017-12-11 22:15:19
Examples: 2017-12-11 22:15:19
Function views
    1. Add an import: 2017-12-11 22:15:19
    2. Add a URL to urlpatterns: 2017-12-11 22:15:19
Class-based views
    1. Add an import: 2017-12-11 22:15:19
    2. Add a URL to urlpatterns: 2017-12-11 22:15:19
Including another URLconf
    1. Import the include() function: 2017-12-11 22:15:19
    2. Add a URL to urlpatterns: 2017-12-11 22:15:19
"""

# from framework
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

# create by us
from basic_management import views
from basic_management import models

urlpatterns = [
    url(r'employee/create/$',
        login_required(views.EmployeeInfoCreate.as_view()),
        name='employee-create'),
    url(r'employee/(?P<pk>\d+)/update/$',
        login_required(views.EmployeeInfoUpdate.as_view()),
        name='employee-update'),
    url(r'employee/(?P<pk>\d+)/delete/$',
        login_required(views.EmployeeInfoDelete.as_view()),
        name='employee-delete'),
    url(r'^employee/$',
        login_required(views.generic_list),
        {'model': models.Employee_Info, 'table_name': 'Employee_Info'},
        name='employee-list'),
    url(r'^employee/search/$',
        login_required(views.employee_search),
        name='employee-search'),
    url(r'^employee/(?P<pk>\d+)$',
        login_required(views.generic_detail),
        {'model': models.Employee_Info, 'table_name': 'Employee_Info'},
        name='employee-detail'),
    url(r'^test/',
        login_required(views.test),
        name='test'),
]

urlpatterns += [
    url(r'company/create/$',
        login_required(views.CompanyInfoCreate.as_view()),
        name='company-create'),
    url(r'company/(?P<pk>\d+)/update/$',
        login_required(views.CompanyInfoUpdate.as_view()),
        name='company-update'),
    url(r'company/(?P<pk>\d+)/delete/$',
        login_required(views.CompanyInfoDelete.as_view()),
        name='company-delete'),
    url(r'^company/$',
        login_required(views.generic_list), {'model': models.Company_Info,
                                             'table_name': 'Company info'},
        name='company-list'),
    url(r'^company/(?P<pk>\d+)$',
        login_required(views.CompanyDetailView.as_view()),
        name='company-detail'),
    url(r'^company/search/$',
        login_required(views.company_search),
        name='company-search'),
]

urlpatterns += [
    url(r'client_info/create/$',
        login_required(views.ClientInfoCreate.as_view()),
        name='client_info-create'),
    url(r'client_info/(?P<pk>\d+)/update/$',
        login_required(views.ClientInfoUpdate.as_view()),
        name='client_info-update'),
    url(r'client_info/(?P<pk>\d+)/delete/$',
        login_required(views.ClientInfoDelete.as_view()),
        name='client_info-delete'),
    url(r'^client_info/$',
        login_required(views.generic_list),
        {'model': models.Client_Info, 'table_name': 'Client_Info'},
        name='client_info-list'),
    url(r'^client_info/(?P<pk>\d+)$',
        login_required(views.generic_detail),
        {'model': models.Client_Info, 'table_name': 'Client_Info'},
        name='client_info-detail'),
    url(r'^client/search/$',
        login_required(views.Client_search),
        name='client-search'),
]

urlpatterns += [
    url(r'product_information/create/$',
        login_required(views.ProductInformationCreate.as_view()),
        name='product_information-create'),
    url(r'product_information/(?P<pk>\d+)/update/$',
        login_required(views.ProductInformationUpdate.as_view()),
        name='product_information-update'),
    url(r'product_information/(?P<pk>\d+)/delete/$',
        login_required(views.ProductInformationDelete.as_view()),
        name='product_information-delete'),
    url(r'^product_information/$',
        login_required(views.generic_list),
        {'model': models.Product_Information, 'table_name': 'Product information'},
        name='product_information-list'),
    url(r'^product_information/(?P<pk>\d+)$',
        login_required(views.generic_detail),
        {'model': models.Product_Information, 'table_name': 'Product information'},
        name='product_information-detail'),
    url(r'product_information/search/$',
        login_required(views.product_search),
        name='product_information-search'),
]

urlpatterns += [
    url(r'categories/create/$',
        login_required(views.CategoriesCreate.as_view()),
        name='categories-create'),
    url(r'categories/(?P<pk>\d+)/update/$',
        login_required(views.CategoriesUpdate.as_view()),
        name='categories-update'),
    url(r'categories/(?P<pk>\d+)/delete/$',
        login_required(views.CategorieDelete.as_view()),
        name='categories-delete'),
    url(r'^categories/$',
        login_required(views.generic_list),
        {'model': models.Categorie, 'table_name': 'Categories'},
        name='categories-list'),
    url(r'categories/search/$',
        login_required(views.Categories_search),
        name='categories-search'),
]

urlpatterns += [
    url(r'manufacturer_information/create/$',
        login_required(views.ManufacturerInformationCreate.as_view()),
        name='manufacturer_information-create'),
    url(r'manufacturer_information/(?P<pk>\d+)/update/$',
        login_required(views.ManufacturerInformationUpdate.as_view()),
        name='manufacturer_information-update'),
    url(r'manufacturer_information/(?P<pk>\d+)/delete/$',
        login_required(views.ManufacturerInformationDelete.as_view()),
        name='manufacturer_information-delete'),
    url(r'^manufacturer/$',
        login_required(views.generic_list),
        {'model': models.Manufacturer_Information,
            'table_name': 'Manufacturer information'},
        name='manufacturer_information-list'),
    url(r'^manufacturer_information/(?P<pk>\d+)$',
        login_required(views.generic_detail),
        {'model': models.Manufacturer_Information,
            'table_name': 'Manufacturer detail'},
        name='manufacturer_information-detail'),
    url(r'manufacturer_information/search/$',
        login_required(views.Manufacturer_search),
        name='manufacturer_information-search'),
]

urlpatterns += [
    url(r'^product_price_request/$',
        views.product_price_request,
        name='product_price_request'),
]

myweb/myweb/urls.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2018-01-08 20:04:44

# -*- coding: utf-8 -*-

"""myweb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see: 2017-12-11 22:18:59
    https: 2017-12-11 22:18:59
Examples: 2017-12-11 22:18:59
Function views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Class-based views
    1. Add an import: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
Including another URLconf
    1. Import the include() function: 2017-12-11 22:18:59
    2. Add a URL to urlpatterns: 2017-12-11 22:18:59
"""

# from framework
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from myweb.views import index, register
from django.contrib.auth.decorators import login_required
# create by us
from myweb.views import index, register

from sales_management import views
from Goods_management import views


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^basic_management/', include('basic_management.urls')),
    url(r'^sales_management/', include('sales_management.urls')),
    url(r'^Goods_management/', include('Goods_management.urls')),
    url(r'^stock/', include('stock.urls')),
    url(r'^accounts/register/$', register, name='register'),
    url(r'^$', login_required(index), name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

myweb/basic_management/models.py
#! /usr/bin/python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
# Last modified: 2017-12-11 22:14:57
from django.db import models
from django.urls import reverse
from m_models.models import AuthUser


class Company_Info(models.Model):

    name = models.CharField('公司名稱', max_length=100)
    address = models.CharField('地址', max_length=200)
    phonenumber = models.CharField('公司電話', max_length=200)
    EIN = models.CharField('統一編號', max_length=50)
    person_in_charge = models.CharField('負責人', max_length=20)
    NUM_employee = models.IntegerField('公司人數', )
    email = models.EmailField(max_length=254)
    introduction = models.TextField('公司簡介', blank=True, null=True)

    class Mate:
        db_table = 'Company_Info'

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('company-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Employee_Info(models.Model):

    M = 'male'
    F = 'female'

    name = models.CharField('員工姓名', max_length=100)
    address = models.CharField('地址', max_length=200)
    email = models.EmailField(max_length=200, null=True)
    phonenumber = models.CharField('電話', max_length=200)
    EMP_gender = ((M, 'male'), (F, 'female'))
    gender = models.CharField('性別', max_length=6, choices=EMP_gender)

    birthday = models.DateField('生日', )

    comp_id = models.ForeignKey(
        Company_Info,
        models.DO_NOTHING,
        verbose_name='所屬公司',
    )
    user = models.ForeignKey(
        AuthUser, models.DO_NOTHING, verbose_name='帳號', blank=True, null=True)

    class Mate:
        db_table = 'Employee_Info'

    def __str__(self):

        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('employee-detail', args=[str(self.id)])


class Client_Info(models.Model):
    M = 'male'
    F = 'female'

    name = models.CharField('客戶名稱', max_length=100)
    address = models.CharField('地址', max_length=200)
    email = models.EmailField(max_length=200, null=True)
    phonenumber = models.CharField('電話', max_length=200)
    CLIENT_gender = ((M, 'male'), (F, 'female'))
    gender = models.CharField('性別', max_length=6, choices=CLIENT_gender)
    birthday = models.DateField('生日', )

    class Mate:
        db_table = 'Client_Info'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('client_info-detail', args=[str(self.id)])


class Categorie(models.Model):
    """Merchandise Categories"""
    name = models.CharField('分類', max_length=100)

    class Mate:
        db_table = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('categories-list')


class Product_Information(models.Model):
    """Product's information"""
    name = models.CharField('產品名稱', max_length=100)
    height = models.FloatField('高度', )
    weight = models.FloatField('重量', )
    price = models.FloatField('價錢', )
    categories_id = models.ForeignKey(
        Categorie,
        on_delete=models.CASCADE,
        verbose_name='商品分類',
    )

    class Mate:
        db_table = 'product_information'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('product_information-detail', args=[str(self.id)])


class Manufacturer_Information(models.Model):
    """Manufacturer's information"""

    name = models.CharField('公司名稱', max_length=100)
    address = models.CharField('地址', max_length=200)
    phonenumber = models.CharField('公司電話', max_length=200)
    EIN = models.CharField('統一編號', max_length=50)
    person_in_charge = models.CharField('負責人', max_length=20)
    NUM_employee = models.IntegerField('公司人數', )
    email = models.EmailField(max_length=254)
    introduction = models.TextField('公司簡介', blank=True, null=True)
    Total_capital = models.IntegerField('資本額', )

    class Mate:
        db_table = 'manufacturer information'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('manufacturer_information-detail', args=[str(self.id)])

myweb/templates/basic_management/categories_list.html
{% extends 'generic_list_base.html' %} 

{% block title %}Categories{% endblock %} 

{% block create_button %}
{% if perms.basic_management.add_categorie %}
<a href="{% url 'categories-create' %}" target="_blank">Create categorie</a>
{% endif %}
{% endblock %} 

{% block table %}
  <form action="{% url 'categories-search'  %}" method="get">
      {% csrf_token %}
      <select name="key">
        <option value="1">分類名稱</option>
      </select> 
        <input type="text" name="name" id='name' placeholder="輸入">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
<table>
    <tr>
        <th>Categorie</th>
        {% if perms.basic_management.change_categorie %}
        <th>Update</th>
        {% endif %}
        {% if perms.basic_management.delete_categorie %}
        <th>Delete</th>
        {% endif %}
    </tr>
    {% for obj in objects %}
    <tr>
        <td>{{obj.name}}</td>
        {% if perms.basic_management.change_categorie %}
        <td>
            <a href="{% url 'categories-update' pk=obj.id %}" target="_blank">Update</a>
        </td>
        {% endif %}
        {% if perms.basic_management.delete_categorie %}
        <td>
            <a href="{% url 'categories-delete' pk=obj.id %}" target="_blank">Delete</a>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

myweb/templates/basic_management/categories_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>分類列表</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>分類</th>			
		

		</tr>
		{%for e in Categories_list%}
		<tr>

			<td>{{e.name}}</td>
			


		</tr>
		{% endfor %}

		</table>

	</div>

	<a href="{% url 'categories-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/basic_management/client_info_list_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>客戶列表</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>客戶名稱</th>
			<th>地址</th>
			<th>email</th>
			<th>電話</th>
			<th>性別</th>
			<th>生日</th>

		</tr>
		{%for c in client_list%}
		<tr>

			<td><a href="/basic_management/client_info/{{c.id}}">{{c.name}}</a></td>
			<td>{{c.address}}</td>
			<td>{{c.email}}</td>
			<td>{{c.phonenumber}}</td>
			<td>{{c.gender}}</td>
			<td>{{c.birthday}}</td>



		</tr>
		{% endfor %}

		</table>

	</div>


	<a href="{% url 'client_info-list' %}">返回列表</a>




</div>

{% endblock %}

myweb/templates/basic_management/company_info_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Company info delete{% endblock %} 

{% block content %}

<p>Are you sure you want to delete the company info: {{ object.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

myweb/templates/basic_management/company_info_detail.html
{% extends 'base.html' %}

{% block title %}Detail of company info{% endblock %}

{% block content %}

<h2>{{table_name}}</h2>

    {% if company_detail %}
    <p><strong>Company name:</strong>{{ company_detail.name }}</p>
    <p><strong>Address:</strong>{{ company_detail.address }}</p>
    <p><strong>Phone number:</strong>{{ company_detail.phonenumber }}</p>
    <p><strong>EIN:</strong>{{ company_detail.EIN }}</p>
    <p><strong>Persion in charge:</strong>{{ company_detail.person_in_charge }}</p>
    <p><strong>Num of employees:</strong>{{ company_detail.NUM_employee }}</p>
    <p><strong>email:</strong>{{ company_detail.email }}</p>
    <p><strong>Introduction:</strong>{{ company_detail.introduction }}</p>
    {% else %}
        <p>There are no company infos.</p>
    {% endif %}
    {% if perms.basic_management.change_company_info %}
    <a href="{% url 'company-update' company_detail.id %}" target="_blank">Update</a>
    {% endif %}
    {% if perms.basic_management.delete_company_info %}
    <a href="{% url 'company-delete' company_detail.id %}" target="_blank">Delete</a>
    {% endif %}
    {% if perms.basic_management.add_company_info %}
    <a href="{% url 'company-create' %}" target="_blank">Create company info</a>
    {% endif %}
{% endblock %}

myweb/templates/basic_management/company_info_form.html
{% extends 'base.html' %} {% block title %}Company info update{% endblock %} {% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

myweb/templates/basic_management/company_info_list.html
{% extends 'generic_list_base.html' %}

{% block title %}List company info{% endblock %}

{% block create_button %}
{% if perms.basic_management.add_company_info %}
<a href="{% url 'company-create' %}" target="_blank">Create company info</a>
{% endif %}
{% endblock %}

{% block table %}
    <form action="{% url 'company-search'  %}" method="get">
      {% csrf_token %}
      <!-- <select name="key">
        <option value="1">公司名稱</option>
        <option value="2">負責人</option>
        <option value="3">電話</option>
      </select> -->
        
    </form>
    
    <table>
        <tr>
        <th>Company name</th>
        <th>Company EIN</th>
        <th>Company introduction</th>
        {% if perms.basic_management.change_company_info %}
        <th>Update</th>
        {% endif %}
        {% if perms.basic_management.delete_company_info %}
        <th>Delete</th>
        {% endif %}
        </tr>
        {% for object in objects %}
        <tr>
        <td><a href="{{object.get_absolute_url}}" target="_blank">{{object.name}}</a></td>
        <td>{{object.EIN}}</td>
        <td>{{object.introduction}}</td>
        {% if perms.basic_management.change_company_info %}
        <td><a href="{% url 'company-update' pk=object.id %}" target="_blank">Update</a></td>
        {% endif %}
        {% if perms.basic_management.delete_company_info %}
        <td><a href="{% url 'company-delete' pk=object.id %}" target="_blank">Delete</a></td>
        {% endif %}
        </tr>
        {% endfor %}
    </table>
{% endblock %}

myweb/templates/basic_management/company_info_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>公司列表</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>公司名稱</th>			
			<th>公司電話</th>
			<th>統一編號</th>
			<th>負責人</th>
			<th>公司人數</th>

		</tr>
		{%for e in company_list%}
		<tr>

			<td><a href="/basic_management/company/{{e.id}}">{{e.name}}</a></td>
			<td>{{e.phonenumber}}</td>
			<td>{{e.EIN}}</td>		
			<td>{{e.person_in_charge}}</td>
			<td>{{e.NUM_employee}}</td>


		</tr>
		{% endfor %}

		</table>

	</div>

	<a href="{% url 'company-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/basic_management/company_infos_list.html
{% extends 'generic_list_base.html' %}

{% block title %}List company info{% endblock %}

{% block create_button %}
{% if perms.basic_management.add_company_info %}
<a href="{% url 'company-create' %}" target="_blank">Create company info</a>
{% endif %}
{% endblock %}

{% block table %}
    <form action="{% url 'company-search'  %}" method="get">
      {% csrf_token %}
      <select name="key">
        <option value="1">公司名稱</option>
        <option value="2">負責人</option>
        <option value="3">電話</option>
      </select>
        <input type="text" name="name" id='name' placeholder="輸入">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <table>
        <tr>
        <th>Company name</th>
        <th>Company EIN</th>
        <th>Company introduction</th>
        {% if perms.basic_management.change_company_info %}
        <th>Update</th>
        {% endif %}
        {% if perms.basic_management.delete_company_info %}
        <th>Delete</th>
        {% endif %}
        </tr>
        {% for object in objects %}
        <tr>
        <td><a href="{{c.get_absolute_url}}" target="_blank">{{object.name}}</a></td>
        <td>{{object.EIN}}</td>
        <td>{{object.introduction}}</td>
        {% if perms.basic_management.change_company_info %}
        <td><a href="{% url 'company-update' pk=object.id %}" target="_blank">Update</a></td>
        {% endif %}
        {% if perms.basic_management.delete_company_info %}
        <td><a href="{% url 'company-delete' pk=object.id %}" target="_blank">Delete</a></td>
        {% endif %}
        </tr>
        {% endfor %}
    </table>
{% endblock %}

myweb/templates/basic_management/employee_info_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>員工列表</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>員工名稱</th>			
			<th>所屬公司</th>
			<th>性別</th>
			<th>帳號</th>
			<th>電話</th>

		</tr>
		{%for e in employee_list%}
		<tr>

			<td><a href="/basic_management/employee/{{e.id}}">{{e.name}}</a></td>
			<td>{{e.comp_id}}</td>
			<td>{{e.gender}}</td>		
			<td>{{e.user}}</td>
			<td>{{e.phonenumber}}</td>


		</tr>
		{% endfor %}

		</table>

	</div>

	<a href="{% url 'employee-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/basic_management/employee_infos_detail.html
{% extends 'base.html' %}

{% block title %}Details of client{% endblock %}

{% block content %}

<h2>{{table_name}}</h2>

    {% if object %}
    <p><strong>Name:</strong>{{ object.name }}</p>
    <p><strong>Address:</strong>{{ object.address }}</p>
    <p><strong>phonenumber:</strong>{{ object.phonenumber }}</p>
    <p><strong>gender:</strong>{{ object.gender }}</p>
    <p><strong>birthday:</strong>{{ object.birthday }}</p>
    <p><strong>Email:</strong>{{ object.email }}</p>
    <p><strong>所屬公司:</strong>{{ object.comp_id }}</p>
    {% else %}
        <p>No detail of employee</p>
    {% endif %}
    <a href="{% url 'employee-update' object.id %}" target="_blank">Update</a>
    <a href="{% url 'employee-delete' object.id %}" target="_blank">Delete</a>
    <a href="{% url 'employee-create' %}" target="_blank">Create new employee</a>
{% endblock %}

myweb/templates/basic_management/employee_infos_list.html
{% extends 'generic_list_base.html' %} 


{% block title %}List Employee info{% endblock %} 

{% block create_button %}
{% if perms.basic_management.add_employee_info %}
<a href="{% url 'employee-create' %}" target="_blank">Create Employee Info</a>
{% endif %}
{% endblock %} 

{% block table %}
        <form action="{% url 'employee-search'  %}" method="get">
            {% csrf_token %}
           <!--  <select name="key">
                <option value="1">員工名稱</option>
                <option value="2">公司</option>
                <option value="3">帳號</option>
                <option value="4">電話</option>

                
            </select>    -->
                員工名稱
                <input type="text" name="name" id='name' placeholder="輸入">
                公司
                <input type="text" name="comp_id" id='name' placeholder="輸入">
                帳號
                <input type="text" name="user" id='name' placeholder="輸入">
                電話
                <input type="text" name="phone" id='name' placeholder="輸入">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>


        </form>

<table>
    <tr>
        <th>隸屬公司</th>
        <th>員工名稱</th>
        <th>地址</th>
        <th>帳號</th>
        <th>電話</th>
        <th>性別</th>
    </tr>
    {% for obj in objects %}
    <tr>
    	<td>{{obj.comp_id}}</td>
        <td>
            <a href="{{obj.get_absolute_url}}" target="_blank">{{obj.name}}</a>
        </td>
        <td>{{obj.address}}</td>
        <td>{{obj.user}}</td>
        <td>{{obj.phonenumber}}</td>
        <td>{{obj.gender}}</td>
        {% if perms.basic_management.change_employee_info %}
        <td>
            <a href="{% url 'employee-update' pk=obj.id %}" target="_blank">Update</a>
        </td>
        {% endif %}
        {% if perms.basic_management.delete_employee_info %}
        <td>
            <a href="{% url 'employee-delete' pk=obj.id %}" target="_blank">Delete</a>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

myweb/templates/basic_management/product_Informations_search.html
{% extends 'base.html' %}

{% block CSS %}
{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'employee.css' %}">
{% endblock %}

{% block title %}basic management{% endblock %}

{% block content %}



<div class="container">
	
	<div class="div-menu">
		<h2>產品列表</h2>
		<form action="" method="get"></form>
		<table class="table table-bordered " >
		<tr>
			
			<th>產品名稱</th>
			<th>高度</th>
			<th>重量</th>
			<th>價錢</th>
			<th>商品分類</th>
	

		</tr>
		{%for e in Product_list%}
		<tr>

			<td><a href="/basic_management/product_information/{{e.id}}">{{e.name}}</a></td>
			<td>{{e.height}}</td>
			<td>{{e.weight}}</td>
			<td>{{e.price}}</td>
			<td>{{e.categories_id}}</td>
			
			


		</tr>
		{% endfor %}

		</table>

	</div>

	<a href="{% url 'product_information-list' %}">返回列表</a>



</div>

{% endblock %}

myweb/templates/basic_management/product_informations_detail.html
{% extends 'base.html' %}

{% block title %}Details of product{% endblock %}

{% block content %}

<h2>{{table_name}}</h2>

    {% if object %}
    <p><strong>Product name:</strong>{{ object.name }}</p>
    <p><strong>Height:</strong>{{ object.height }}</p>
    <p><strong>Weight:</strong>{{ object.weight }}</p>
    <p><strong>Price:</strong>{{ object.price }}</p>
    <p><strong>Categorie:</strong>{{ object.categories_id }}</p>
    {% else %}
        <p>No detail of product.</p>
    {% endif %}
    {% if perms.basic_management.change_product_information %}
    <a href="{% url 'product_information-update' object.id %}" target="_blank">Update</a>
    {% endif %}
    {% if perms.basic_management.delete_product_information %}
    <a href="{% url 'product_information-delete' object.id %}" target="_blank">Delete</a>
    {% endif %}
    {% if perms.basic_management.add_product_information %}
    <a href="{% url 'product_information-create' %}" target="_blank">Create new product</a>
    {% endif %}
{% endblock %}